version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - info
      - compile:
          requires: 
            - info
      - link:
          requires: 
            - compile


jobs:
  info:
    parallelism: 2
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: hostname
      - run: echo $CIRCLE_NODE_TOTAL
      - run: echo $CIRCLE_NODE_INDEX
      - run: set

  compile:
    parallelism: 5
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: git clone git@github.com:eddiewebb/linux.git

  link:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: git clone git@github.com:eddiewebb/linux.git
