version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - info
      - compile:
          requires: 
            - info
      - compile-2:
          requires: 
            - info
      - link:
          requires: 
            - compile


jobs:
  info:
    parallelism: 2
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: hostname
      - run: echo $CIRCLE_NODE_TOTAL
      - run: echo $CIRCLE_NODE_INDEX
      - run: set

# cache restore takes longer than shallow clone
  compile:
    #parallelism: 2
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts && chmod 0600 ~/.ssh/known_hosts
      - restore_cache:
          keys:
            - kernel-source-shallow
      - run: |
          if [ -e .git ]
          then
            git remote set-url origin git@github.com:eddiewebb/linux.git || true
            git pull
          else
            git clone --depth=1 git@github.com:eddiewebb/linux.git .
          fi
      - save_cache:
          key: kernel-source-shallow
          paths:
            - ".git"
      - run: du -hs .

  compile:
    #parallelism: 5
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts && chmod 0600 ~/.ssh/known_hosts
      - run: git clone --depth=1 git@github.com:eddiewebb/linux.git .
      - run: du -hs .
      - run: make

  link:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo ""
