version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - info
      - compile:
          requires: 
            - info
      - link:
          requires: 
            - compile


jobs:
  info:
    parallelism: 2
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: hostname
      - run: echo $CIRCLE_NODE_TOTAL
      - run: echo $CIRCLE_NODE_INDEX
      - run: set

# cache restore takes longer than shallow clone
  compile:
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - circleci tests glob "**/*.c" | circleci tests split --split-by=filesize | xargs gcc -c 
      - mkdir output && mv *.o output
      - persist_to_workspace:
          root: output
          paths:
            - *.o


  link:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: output
      - run: mv output/* .
      - run: gcc -o program *.o


