version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - info
      - compile:
          requires: 
            - info
      - link:
          requires: 
            - compile


jobs:
  info:
    parallelism: 2
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: hostname
      - run: echo $CIRCLE_NODE_TOTAL
      - run: echo $CIRCLE_NODE_INDEX
      - run: set

  compile:
    #parallelism: 5
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts && chmod 0600 ~/.ssh/known_hosts
      - restore_cache:
          keys:
            - kernel-source
      - run: git clone --depth=1 git@github.com:eddiewebb/linux.git .
      - save_cache:
          key: kernel-source
          paths:
            - ".git"
      - run: du -hs .

  link:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo ""
